services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=hqysxvqw5cgdYyQHTfHe # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=Kanelson # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - sqlvolume:/var/lib/postgresql/data
  kanelson:
    image: kanelson
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__KanelsonDb=User ID=postgres;Password=hqysxvqw5cgdYyQHTfHe;Host=localhost;Port=5432;Database=Kanelson;Pooling=true;Maximum Pool Size=5;Multiplexing=true
    depends_on: 
      - db
    ports:
      - "7289:8080"
volumes:
  sqlvolume: