services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "kanelson_user"
      POSTGRES_PASSWORD: "Postgres!"
      POSTGRES_DB: "kanelsondb"    
    
    ports:
      - "5432:5432"
  kanelson:
    image: kanelson
    build:
      context: .
      dockerfile: Dockerfile
      
    environment:
      ConnectionStrings__Postgres: "host=postgres;port=5432;database=kanelsondb;username=kanelson_user;password=Postgres!"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on: 
      - postgres
    ports:
      - "7918:7918"
      - "7289:80"